services:
  - type: web
    name: gamebird-app
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
